version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: flash_card_App_DB
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    

